name: keypoint_moseq
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.6.0=h6a678d5_0
  - blas=1.0=mkl
  - blosc=1.21.3=h6a678d5_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h5eee18b_5
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.3.11=h06a4308_0
  - cfitsio=3.470=h5893167_7
  - charls=2.2.0=h2531618_0
  - dav1d=1.2.1=h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - imagecodecs=2023.1.23=py39hc4b7b5f_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9e=h5eee18b_1
  - jxrlib=1.1=h7b6447c_2
  - krb5=1.20.1=h143b758_1
  - lazy_loader=0.3=py39h06a4308_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libavif=0.11.1=h5eee18b_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcurl=8.5.0=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=h6a678d5_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libzopfli=1.0.3=he6710b0_0
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  - ncurses=6.4=h6a678d5_0
  - networkx=3.1=py39h06a4308_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_0
  - pip=23.2.1=py39h06a4308_0
  - python=3.9.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - scikit-image=0.22.0=py39h1128e8f_0
  - setuptools=68.0.0=py39h06a4308_0
  - snappy=1.1.10=h6a678d5_1
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tifffile=2023.4.12=py39h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zfp=1.0.0=h6a678d5_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.0.0
      - anyio==4.0.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.4.0
      - async-lru==2.0.4
      - attrs==23.1.0
      - av==10.0.0
      - babel==2.12.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - blosc2==2.0.0
      - bokeh==2.4.3
      - certifi==2023.7.22
      - cffi==1.15.1
      - charset-normalizer==3.2.0
      - chex==0.1.6
      - cloudpickle==2.2.1
      - colorcet==3.0.1
      - comm==0.1.4
      - commentjson==0.9.0
      - contourpy==1.3.0
      - cycler==0.11.0
      - cython==3.0.2
      - cytoolz==0.12.2
      - debugpy==1.8.0
      - decorator==4.4.2
      - defusedxml==0.7.1
      - dm-tree==0.1.8
      - dynamax==0.1.2
      - etils==1.5.0
      - exceptiongroup==1.1.3
      - executing==1.2.0
      - fastjsonschema==2.18.0
      - fastprogress==1.0.3
      - fonttools==4.42.1
      - fqdn==1.5.1
      - fsspec==2023.9.2
      - gast==0.5.4
      - h5py==3.9.0
      - hdmf==3.9.0
      - holoviews==1.15.4
      - idna==3.4
      - imageio==2.31.3
      - imageio-ffmpeg==0.4.9
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.0
      - ipykernel==6.25.2
      - ipython==8.15.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.5.1
      - isoduration==20.11.0
      - jax==0.3.22
      - jax-moseq==0.3.0
      - jaxlib==0.3.22+cuda11.cudnn82
      - jaxtyping==0.2.14
      - jedi==0.19.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - jupyter-bokeh==2.0.3
      - jupyter-client==8.3.1
      - jupyter-contrib-core==0.4.2
      - jupyter-core==5.3.1
      - jupyter-events==0.7.0
      - jupyter-lsp==2.2.0
      - jupyter-nbextensions-configurator==0.6.3
      - jupyter-server==2.7.3
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.6
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.25.0
      - keypoint-moseq==0.5.0
      - kiwisolver==1.4.5
      - lark-parser==0.7.8
      - linkify-it-py==2.0.2
      - llvmlite==0.41.0
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.6
      - mdit-py-plugins==0.4.0
      - mdurl==0.1.2
      - mistune==3.0.1
      - moviepy==1.0.3
      - msgpack==1.0.6
      - natsort==8.4.0
      - nbclient==0.8.0
      - nbconvert==7.8.0
      - nbformat==5.9.2
      - ndx-pose==0.1.1
      - nest-asyncio==1.5.8
      - notebook==6.1.5
      - notebook-shim==0.2.3
      - numba==0.58.0
      - numexpr==2.8.6
      - numpy==1.24.4
      - opencv-python-headless==4.8.0.76
      - opt-einsum==3.3.0
      - optax==0.1.7
      - optree==0.9.2
      - overrides==7.4.0
      - packaging==23.1
      - pandas==2.1.1
      - pandocfilters==1.5.0
      - panel==0.14.4
      - param==1.13.0
      - parso==0.8.3
      - patsy==0.5.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.1
      - platformdirs==3.10.0
      - plotly==5.17.0
      - proglog==0.1.10
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pycparser==2.21
      - pyct==0.5.0
      - pygments==2.16.1
      - pynndescent==0.5.11
      - pynwb==2.5.0
      - pyparsing==3.1.1
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pyviz-comms==3.0.0
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - qgrid==1.3.1
      - referencing==0.30.2
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.10.3
      - ruamel-yaml==0.17.32
      - ruamel-yaml-clib==0.2.7
      - rupture==1.4.5
      - ruptures==1.1.9
      - scikit-learn==1.3.1
      - scipy==1.11.2
      - seaborn==0.13.0
      - send2trash==1.8.2
      - simplejson==3.19.1
      - six==1.16.0
      - sleap-io==0.0.11
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.2
      - statsmodels==0.14.0
      - tables==3.8.0
      - tabulate==0.9.0
      - tenacity==8.2.3
      - tensorflow-probability==0.19.0
      - terminado==0.17.1
      - threadpoolctl==3.2.0
      - tinycss2==1.2.1
      - tomli==2.0.1
      - toolz==0.12.0
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.10.0
      - typeguard==4.1.5
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - uc-micro-py==1.0.2
      - umap-learn==0.5.5
      - uri-template==1.3.0
      - urllib3==2.0.5
      - vidio==0.0.4
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.3
      - widgetsnbextension==3.5.2
      - xyzservices==2023.7.0
      - zipp==3.17.0
prefix: /home/linda/miniconda3/envs/keypoint_moseq
